### PR TITLE
[Do not Merge] typo: Double words

### PR DESCRIPTION
**Pull request by nschonni**
Opening this as a PR as it's easier to show all the places than trying to point to lines so you can trace back to the upstream sources

### CODE REVIEW

**Comment by imwiss** [comment]
Thanks @nschonni! I've added it to our backlog so that we can address this at the source. Appreciate you opening the PR.

**Comment by nschonni** [comment]
FYI, just reran vale on the head of the default branch and still got these hits
````
←[4mdescriptions\ghes-2.18\ghes-2.18.json←[0m
 2244:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\api.github.com\api.github.com.json←[0m
 3563:66    ←[31merror←[0m  'that' is repeated!  Vale.Repetition
 39685:344  ←[31merror←[0m  'for' is repeated!   Vale.Repetition


 ←[4mdescriptions\ghes-2.19\ghes-2.19.json←[0m
 2244:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition 


 ←[4mdescriptions\ghes-2.20\ghes-2.20.json←[0m
 2240:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.18\dereferenced\ghes-2.18.deref.json←[0m
 4448:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.19\dereferenced\ghes-2.19.deref.json←[0m
 4450:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition 


 ←[4mdescriptions\ghes-2.21\ghes-2.21.json←[0m
 2240:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.20\dereferenced\ghes-2.20.deref.json←[0m
 4446:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\api.github.com\dereferenced\api.github.com.deref.json←[0m
 18273:66    ←[31merror←[0m  'that' is repeated!  Vale.Repetition
 267566:344  ←[31merror←[0m  'for' is repeated!   Vale.Repetition


 ←[4mdescriptions\ghes-2.22\ghes-2.22.json←[0m
 2244:232  ←[31merror←[0m  'the' is repeated!   Vale.Repetition
 5111:66   ←[31merror←[0m  'that' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-3.0\ghes-3.0.json←[0m
 2244:232  ←[31merror←[0m  'the' is repeated!   Vale.Repetition
 5820:66   ←[31merror←[0m  'that' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.21\dereferenced\ghes-2.21.deref.json←[0m
 4446:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.22\dereferenced\ghes-2.22.deref.json←[0m
 4450:232  ←[31merror←[0m  'the' is repeated!   Vale.Repetition
 21369:66  ←[31merror←[0m  'that' is repeated!  Vale.Repetition 


 ←[4mdescriptions\ghes-3.0\dereferenced\ghes-3.0.deref.json←[0m
 4450:232  ←[31merror←[0m  'the' is repeated!   Vale.Repetition
 23645:66  ←[31merror←[0m  'that' is repeated!  Vale.Repetition 
```

**Comment by xuorig** [comment]
Oops didnt mean to close this @nschonni! Re opening.

**Comment by nschonni** [comment]
@xuorig no worries, I rebased and added some new ones so it's easier to trace back to the source strings

**Comment by ahoglund** [comment]
Resolved by https://github.com/github/rest-api-description/pull/199

**Comment by nschonni** [comment]
@ahoglund there are still a few 
```
$ vale .

 ←[4mdescriptions\ghes-2.18\ghes-2.18.json←[0m
 2244:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.18\dereferenced\ghes-2.18.deref.json←[0m
 4448:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.22\ghes-2.22.json←[0m
 2244:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-3.0\ghes-3.0.json←[0m
 2244:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-2.22\dereferenced\ghes-2.22.deref.json←[0m
 4450:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition


 ←[4mdescriptions\ghes-3.0\dereferenced\ghes-3.0.deref.json←[0m
 4450:232  ←[31merror←[0m  'the' is repeated!  Vale.Repetition

✖ ←[31m6 errors←[0m, ←[33m0 warnings←[0m and ←[34m0 suggestions←[0m in 24 files.
```

**Pull request closed without merging**
